### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by hspotlight** [hspotlight/metro-fare#45]
I would like to enable this application to run in docker container.

**Acceptance Criteria**
As a maintainer,
I would like to run application in container while development,
so that it every maintainer has the same environment and it makes sure that it can run in production (Netlify)

As a Hacktoberfest contributor,
I would like to run application  in docker,
so that it would not conflict with my local environment.

Thank you.

**Comment by jonbrohauge** [comment]
@hspotlight  I'd like to contribute to this issue.

**Comment by hspotlight** [comment]
@jonbrohauge  Hi thank you. Please go ahead. :)
